sudo: required
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk10
  - oraclejdk11
  - openjdk11
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

script:
  - if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then ./mvnw -U install; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN; fi
